version: '3.8'
services:
  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - '5000:5000'  # optional; can be removed in strict production
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - frontend/.env
    ports:
      - '3000:80'
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
