version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: appdb
      PORT: 3000
    ports:
      - '4000:3000'
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3000
    ports:
      - '3000:80'
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
