name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Backend install and test
        working-directory: backend
        run: |
          npm ci
          npm run lint || true
          npm test || true

      - name: Frontend install and test
        working-directory: frontend
        run: |
          npm ci
          npm run lint || true
          npm test || true

      - name: Build images
        run: docker-compose build --pull

      - name: Bring up stack
        run: docker-compose up -d --build

      - name: Run smoke tests
        run: |
          sleep 10
          curl --fail http://localhost:4000/metrics || true
